spring:
  mvc:
    favicon:
      enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/server_test?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
